### ISSUE TITLE
"WARNING: done not called!" masking real errors

### ISSUE THREAD

**Issue by rodneyrehm** [dalekjs/dalek#12]
I'm not getting error messages / stack traces of problems my tests may have. Instead I'm presented with the utterly useless (and easy to miss) message "WARNING: done not called!".

I need to see what I did wrong here. Tests need to halt. This is a JavaScript error. I tried to invoke a function that doesn't exist. My test is flawed - stop and yell!

``` javascript
{
  foo: function(test) {
    test
      // Note that this should be .assert.doesntExist()
      .doesntExist('.selector')
      // this isn't called
      .done();
  }
}
```

**Comment by bowsersenior** [comment]
How is this fixed? I'm using 0.0.9 and errors are still hidden.

```javascript
//error.js
module.exports = {

  'Error inside test chain': function (test) {
    test
      .badFunctionName()
      .done();

  },

  'Error outside test chain': function (test) {
    badFunctionName();

    test
      .done();
  },

  foo: function(test) {
    test
      // Note that this should be .assert.doesntExist()
      .doesntExist('.selector')
      // this isn't called
      .done();
  }

};
```

```bash
$ dalek error.js
Running tests
Running Browser: PhantomJS
OS: mac 10.10 (Yosemite) 32bit
Browser Version: 1.9.8
>> WARNING: done() not called before timeout!

RUNNING TEST - "Error inside test chain"
>> WARNING: done() not called before timeout!

RUNNING TEST - "Error outside test chain"
>> WARNING: done() not called before timeout!

RUNNING TEST - "foo"
✔ 0 Assertions run
✔ TEST - "foo" SUCCEEDED

 0/0 assertions passed. Elapsed Time: 31.01 sec 
```

**Comment by SarahPAV** [comment]
Also having the same issue as @bowsersenior.

I'm using the following versions:
DalekJS CLI Tools Version: 0.0.5
DalekJS  local install: 0.0.9

Syntax errors do not entail an error in command line - see the mistake ```.assert.text.to.contain('#i_am_a_textbox', 'TEXT')``` in the code block below. After changing this syntax mistake to ```.assert.text('#i_am_a_textbox').to.contain('TEXT')```, a real error did show up in console.

 - Test Code:

```
module.exports = {
	'Dalek test': function (test) {
		test
			.open('http://www.dalekjs.com/guineapig/')
			.type('#i_am_a_textbox', 'TEXT')
			.assert.text.to.contain('#i_am_a_textbox', 'TEXT')
			.done();
	}
};
```

 - Command Line Output:

```
$ dalek tests/dalekTest.js -b phantomjs
Running tests
Running Browser: PhantomJS
OS: linux unknown 64bit
Browser Version: 1.9.8
>> WARNING: done() not called before timeout!

RUNNING TEST - "Dalek test"
▶ OPEN http://www.dalekjs.com/guineapig/
▶ TYPE #i_am_a_textbox
✔ 0 Assertions run
✔ TEST - "Dalek test" SUCCEEDED
```

**Comment by herlon214** [comment]
@SarahPAV , I solved this error by checking the correct commands.
In my case I typed "screenshot" wrong so it never continues the flow until the .done()

I holpe it helps you.
