### ISSUE TITLE
`Running tests` and nothing else

### ISSUE THREAD

**Issue by greenkey** [dalekjs/dalek#146]
Hi, I'm trying to make a Dockerfile to run Dalek:

```Dockerfile
FROM ubuntu:14.04
MAINTAINER Lorenzo Mele <lorenzo@nospam.com>

# update packages before install
RUN apt-get update

# install nodejs
RUN apt-get install nodejs npm -y
RUN ln `which nodejs` /usr/bin/node

# install Dalekjs
RUN npm install dalek-cli -g
# install the Dalek base framework & all its dependencies
RUN npm install dalekjs --save-dev
```

Then I built the image:
`sudo docker build -t "local/dalek" .`
Finally I entered in the VM:
`sudo docker run -i -t "local/dalek" /bin/bash`

I created the file `test/my_first_test.js` as described [here](http://dalekjs.com/pages/getStarted.html), then I launch the test and this is what appens:
```shell
root@a4a525e451da:/mnt/cwd# dalek test/my_first_test.js  -l 5
Running tests
☁ [SYSTEM] dalek-internal-driver: Loading driver: "native"
root@a4a525e451da:/mnt/cwd# 
```

What am I missing to make the test work?

**Comment by bobjflong** [comment]
I just had this problem, where I got the output:

```
$ dalek test/test.js -b chrome -l 5
Running tests
☁ [SYSTEM] dalek-internal-driver: Loading driver: "native"
```

I tried node `0.10.25` and `0.10.30`.

I fixed the issue by deleting `node_modules` and re-running `npm install`. My issue may have been caused by copying over a `node_modules` from a different machine.

**Comment by yvess** [comment]
I have the same problem. Only getting "Running tests"

Here are my versions

```bash
root@9d69733fb491:/# nodejs -v
v0.10.36

root@dabe0d2b6dc5:/# npm list -g
/usr/lib
├─┬ dalek-cli@0.0.5
└─┬ npm@1.4.28
...

  root@dabe0d2b6dc5:/# npm list
/
└─┬ dalekjs@0.0.9
  ├─┬ dalek-browser-phantomjs@0.0.4
  │ ├─┬ phantomjs@1.9.12
  ├─┬ dalek-driver-native@0.0.6
  │ ├─┬ dalek-internal-webdriver@0.0.5
...
```

You can reproduce it by running `docker run -it --rm yvess/drone-fig bash -l` and than run `dalek /root/test.js` 
The same same test.js file works on my mac. 
Any idea what could be the problem? 
All the node_models are freshly downloaded not copied from another place.

**Comment by yvess** [comment]
Ok solved the problem. This is quite a basic docker image, no font stuff installed. When I installed phantomjs separately and tried to run it there was an error, no libfreetype etc. 

After installing the missing libs it worked. 

```
apt-get install fontconfig-config fonts-dejavu-core libfontconfig1 libfreetype6 libjpeg-turbo8 libjpeg8
``` 

Perhaps it would be good if the phantomjs errors would be propagated, so that you see them.

**Comment by greenkey** [comment]
Well sorry for the huge late reply, but it's working!
Many thanks to @yvess
